version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" #
    schedule:
      interval: "daily"
      timezone: "Asia/Baghdad"
      time: "20:00"
    
    target-branch: "development"
    
    labels:
      - "pip dependencies"